# Generated by Django 3.0.2 on 2020-04-04 22:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avian14to17Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='SOME STRING', max_length=250)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('region', models.CharField(default='SOME STRING', max_length=250)),
                ('country', models.CharField(default='SOME STRING', max_length=250)),
                ('admin1', models.CharField(default='SOME STRING', max_length=250)),
                ('localityName', models.CharField(default='SOME STRING', max_length=250)),
                ('localityQuality', models.CharField(default='SOME STRING', max_length=250)),
                ('observationDate', models.CharField(default='SOME STRING', max_length=250)),
                ('reportingDate', models.CharField(default='SOME STRING', max_length=250)),
                ('status', models.CharField(default='SOME STRING', max_length=250)),
                ('disease', models.CharField(default='SOME STRING', max_length=250)),
                ('serotypes', models.CharField(default='SOME STRING', max_length=250)),
                ('speciesDescription', models.CharField(default='SOME STRING', max_length=250)),
                ('sumAtRisk', models.CharField(default='SOME STRING', max_length=250)),
                ('sumCases', models.FloatField(default=0)),
                ('sumDeaths', models.FloatField(default=0)),
                ('sumDestroyed', models.FloatField(default=0)),
                ('sumSlaughtered', models.FloatField(default=0)),
                ('humansGenderDesc', models.CharField(default='SOME STRING', max_length=250)),
                ('humansAge', models.FloatField(default=0)),
                ('humansAffected', models.FloatField(default=0)),
                ('humansDeath', models.FloatField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Avian Data 2014-2017',
            },
        ),
        migrations.CreateModel(
            name='EmpresDomesticWildHuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='SOME STRING', max_length=250)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(default='SOME STRING', max_length=250)),
                ('country', models.CharField(default='SOME STRING', max_length=250)),
                ('admin1', models.CharField(default='SOME STRING', max_length=250)),
                ('localityName', models.CharField(default='SOME STRING', max_length=250)),
                ('localityQuality', models.CharField(default='SOME STRING', max_length=250)),
                ('observationDate', models.CharField(default='SOME STRING', max_length=250)),
                ('reportingDate', models.CharField(default='SOME STRING', max_length=250)),
                ('reportingYear', models.FloatField(default=0)),
                ('serotypes', models.CharField(default='SOME STRING', max_length=250)),
                ('birdType', models.CharField(default='SOME STRING', max_length=250)),
                ('speciesDescription', models.CharField(default='SOME STRING', max_length=250)),
                ('sumAtRisk', models.FloatField(default=0)),
                ('sumCases', models.FloatField(default=0)),
                ('sumDeaths', models.FloatField(default=0)),
                ('sumDestroyed', models.FloatField(default=0)),
                ('sumSlaughtered', models.FloatField(default=0)),
                ('humansGenderDesc', models.CharField(default='SOME STRING', max_length=250)),
                ('humansAge', models.FloatField(default=0)),
                ('humansAffected', models.FloatField(default=0)),
                ('humansDeaths', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Empres Domestic Wild Human',
            },
        ),
        migrations.CreateModel(
            name='EmpresTwoYearOutbreakData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='SOME STRING', max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('serotypes', models.CharField(default='SOME STRING', max_length=250)),
                ('speciesDescription', models.CharField(default='SOME STRING', max_length=250)),
                ('country', models.CharField(default='SOME STRING', max_length=250)),
                ('sumCases', models.FloatField(default=0)),
                ('sumDeaths', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Empres Two Year Outbreak Data',
            },
        ),
        migrations.CreateModel(
            name='GisaidEpifluEuropeIsolateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_id', models.CharField(default='SOME STRING', max_length=250)),
                ('isolate_name', models.CharField(default='SOME STRING', max_length=250)),
                ('subtype', models.CharField(default='SOME STRING', max_length=250)),
                ('passage_history', models.CharField(default='SOME STRING', max_length=250)),
                ('location', models.CharField(default='SOME STRING', max_length=250)),
                ('host', models.CharField(default='SOME STRING', max_length=250)),
                ('collection_date', models.CharField(default='SOME STRING', max_length=250)),
                ('update_date', models.CharField(default='SOME STRING', max_length=250)),
                ('submission_date', models.CharField(default='SOME STRING', max_length=250)),
                ('host_gender', models.CharField(default='SOME STRING', max_length=250)),
                ('animal_specimen_source', models.CharField(default='SOME STRING', max_length=250)),
                ('animal_health_status', models.CharField(default='SOME STRING', max_length=250)),
                ('domestic_status', models.CharField(default='SOME STRING', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Gisaid Epiflu Europe Isolate Data',
            },
        ),
        migrations.CreateModel(
            name='HumanCasesDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_institution', models.CharField(default='SOME STRING', max_length=250)),
                ('host_identifier', models.CharField(default='SOME STRING', max_length=250)),
                ('collection_year', models.FloatField(default=0)),
                ('collection_season', models.CharField(default='SOME STRING', max_length=250)),
                ('country', models.CharField(default='SOME STRING', max_length=250)),
                ('state', models.CharField(default='SOME STRING', max_length=250)),
                ('city', models.CharField(default='SOME STRING', max_length=250)),
                ('age', models.FloatField(default=0)),
                ('gender', models.CharField(default='SOME STRING', max_length=250)),
                ('subtype', models.CharField(default='SOME STRING', max_length=250)),
                ('flu_type', models.CharField(default='SOME STRING', max_length=250)),
                ('strain_name', models.CharField(default='SOME STRING', max_length=250)),
                ('flu_test_status', models.CharField(default='SOME STRING', max_length=250)),
                ('sample_type', models.CharField(default='SOME STRING', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Human Cases Data',
            },
        ),
        migrations.CreateModel(
            name='OpenFluFlockOutbreakData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofl_isolate_id', models.CharField(default='SOME STRING', max_length=250)),
                ('name', models.CharField(default='SOME STRING', max_length=250)),
                ('type', models.CharField(default='SOME STRING', max_length=250)),
                ('h5_clade', models.CharField(default='SOME STRING', max_length=250)),
                ('passage', models.CharField(default='SOME STRING', max_length=250)),
                ('collect_date', models.CharField(default='SOME STRING', max_length=250)),
                ('host', models.CharField(default='SOME STRING', max_length=250)),
                ('location', models.CharField(default='SOME STRING', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Open-Flu Flock Outbreak Data',
            },
        ),
    ]
